### ISSUE TITLE
New Logo Design

### ISSUE THREAD

**Issue by Tobaloidee** [MalloZup/missile#2]
Hi @MalloZup  Tobaloidee here again, I have designed a new logo for this specific project Sir..I hope you like it again! I created a Missile Chat logo to be a perfect fit for this project because i wanted it to be unique and different to the fullrocketmetal design.
![MISSILE pres-05](https://user-images.githubusercontent.com/36028424/55288093-149d9a80-53e5-11e9-9577-29592ae51bec.png)

**Comment by MalloZup** [comment]
Awesome @Tobaloidee 😍😍feel free to send a Pr for the Readme and replace the custom one thx ❤️❤️

**Comment by Tobaloidee** [comment]
Hi @MalloZup  Here's the PR #3 for the logo upload and readme update..Also, you can download and use all the formats and variations on this [LINK](https://drive.google.com/drive/u/1/folders/1CLD2kN_e0D7Yf8gJ1KIz_a1rZIf-_b2s) to my drive.

Just contact me when you need any help regarding logo design Sir.

Thanks & Best regards!
-Tobaloidee

**Comment by MalloZup** [comment]
Thx à lof it is beautiful

**Comment by Tobaloidee** [comment]
You're welcome! if you need logo designs in the future, just let me know.👍
